name: Release

on:
  release:
    types: [published]

jobs:
  release_zip:
    name: Release zip
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Create token_extractor.zip
        run: |
          mkdir -p token_extractor
          cp token_extractor.py token_extractor/
          cp requirements.txt token_extractor/
          zip token_extractor.zip -r token_extractor
          rm -rf token_extractor

      - name: Archive built file
        uses: actions/upload-artifact@v4
        with:
          name: token_extractor.zip
          path: token_extractor.zip

      - name: Upload token_extractor.zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: token_extractor.zip
          asset_name: token_extractor.zip
          tag: ${{ github.ref }}
          overwrite: true

  release_docker_zip:
    name: Release docker zip
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Create token_extractor.zip
        run: |
          mkdir -p token_extractor_docker
          cp token_extractor.py token_extractor_docker/
          cp requirements.txt token_extractor_docker/
          cp .dockerignore token_extractor_docker/
          cp Dockerfile token_extractor_docker/
          zip token_extractor_docker.zip -r token_extractor_docker
          rm -rf token_extractor_docker

      - name: Archive built file
        uses: actions/upload-artifact@v4
        with:
          name: token_extractor_docker.zip
          path: token_extractor_docker.zip

      - name: Upload token_extractor.zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: token_extractor_docker.zip
          asset_name: token_extractor_docker.zip
          tag: ${{ github.ref }}
          overwrite: true

  release_exe:
    name: Release exe
    runs-on: windows-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.13.x'

      - name: Install pyinstaller
        run: pip3 install -U pyinstaller

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run pyinstaller
        run: pyinstaller token_extractor.spec

      - name: Archive built file
        uses: actions/upload-artifact@v4
        with:
          name: token_extractor.exe
          path: dist/token_extractor.exe

      - name: Upload token_extractor.exe to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/token_extractor.exe
          asset_name: token_extractor.exe
          tag: ${{ github.ref }}
          overwrite: true
